### ISSUE TITLE
Missing `"ember-inflector": "2.2.0"` in package.json!

### ISSUE THREAD

**Issue by batwell31** [udacity/FEF-Quiz-Ember-Component#1]
My application won't load anything unless I put `"ember-inflector": "2.2.0",`  in the `package.json` file under `"devDependencies"` .  This might just be a windows issue.  I'm not exactly 100 percent sure, but I've found this fixes the problem for me.  I've also read that other people have had the same issue.

**Comment by chrisjulson** [comment]
the addition of "ember-inflector": "2.2.0" to "devDependencies" in the package.json file does fix the display issue and it seems to be the same issue with all the Ember Quiz repos.
